name: WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev build-essential
      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
            components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -A renamed_and_removed_lints -A clippy::new-ret-no-self -D warnings
          name: clippy
  
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev build-essential
    - name: Install rustfmt with nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path=Cargo.toml --all -- --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install deps
      if: matrix.platform == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev build-essential

    - name: Get current date
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Get current date
      if: matrix.os == 'windows-latest'
      run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        # Add date to the cache to keep it up to date
        key: ${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        # Add date to the cache to keep it up to date
        key: ${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: /target
        # Add date to the cache to keep it up to date
        key: ${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=Cargo.toml --all --release

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=Cargo.toml --all-targets --all-features

  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    run: |
      sudo apt-get update
      sudo apt-get install -y libudev-dev
    steps:
    - uses: actions/checkout@v2
    - name: Install rustfmt with nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: fuzz
    - uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: --manifest-path=Cargo.toml build
